apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-bus
  template:
    metadata:
      labels:
        app: event-bus
    spec:
      containers:
      - name: event-bus
        image: localhost:5000/event-bus:v1
        ports:
        - containerPort: 4005
